"""2st

Revision ID: 65affe0e0f71
Revises: 488d26dffcf7
Create Date: 2020-09-21 01:03:04.727908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65affe0e0f71'
down_revision = '488d26dffcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
